name: ussd
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_phone_direct_caller: ^2.1.1
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_flavorizr: ^2.1.6

flutter:
  uses-material-design: true

flavorizr:
  ide: vscode
  flavors:
    vodafone:
      app:
        name: "Vodafone Cash"
      android:
        applicationId: "dev.lasheen.ussd.vodafone"
      ios:
        bundleId: "com.example.apple"
    orange:
      app:
        name: "Orange Cash"
      android:
        applicationId: "dev.lasheen.ussd.orange"
      ios:
        bundleId: "com.example.apple"