name: ussd
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_phone_direct_caller: ^2.1.1
  google_fonts: ^4.0.3
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_flavorizr: ^2.2.1 

flutter:
  uses-material-design: true

flavorizr:
  ide: vscode
  flavors:
    vodafone:
      app:
        name: "Vodafone Codes"
        icon: "/var/mnt/fastD/design/Apps/ussd/vodafone.png"
      android:
        applicationId: "dev.lasheen.ussd.vodafone"

    orange:
      app:
        name: "Orange Codes"
        icon: "/var/mnt/fastD/design/Apps/ussd/orange.png"
      android:
        applicationId: "dev.lasheen.ussd.orange"

    we:
      app:
        name: "We Codes"
        icon: "/var/mnt/fastD/design/Apps/ussd/we.png"
      android:
        applicationId: "dev.lasheen.ussd.we"

    etisalat:
      app:
        name: "Etisalat Codes"
        icon: "/var/mnt/fastD/design/Apps/ussd/etisalat.png"  
      android:
        applicationId: "dev.lasheen.ussd.etisalat"
